### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [AleksandraKaminska/NavyPlayer-deezer-#2]
Hi @AleksandraKaminska, Im a Graphic Designer that likes to contribute to open source projects, I would like to know if you need a logo for you project? I would like to work with you and in this project.

If you want just tell me what you want for the logo?

Greetings!

**Comment by AleksandraKaminska** [comment]
Hi @zuurw, 
I didn't think about this, but if you want to have something in your portfolio, go ahead. I have no idea about design so give free rein.

**Comment by zuurw** [comment]
Hello @AleksandraKaminska, you have a great project here, I saw the website and it looks really good.

For the design I was thinking to make something simple and modern, what kind of stuff do you prefair for the logo? a player button? soundwave? I can do something with the letter N (navy).

I will start to design your logo today!

Best Regards!

**Comment by AleksandraKaminska** [comment]
Hi, thank you. I think soundwave will be the best.

**Comment by zuurw** [comment]
Hi @AleksandraKaminska, I create this designs for your project, and I create a screenshot of the logos in your website to see how they look there.

![navy proposal](https://user-images.githubusercontent.com/40801473/42389035-51ccdb6a-813f-11e8-8484-fe43ae3dbeab.png)

**Comment by AleksandraKaminska** [comment]
Wow thank you, this is awesome.

**Comment by zuurw** [comment]
Thanks, Im happy you like it.

Which version do you want?

Cheers.

**Comment by AleksandraKaminska** [comment]
Hi, I like the third one.
